"use client";

import React, { useEffect, useState } from "react";
import ConfigProvider from "./config-provider";
import "./globals.css";
import Navigation from "@/components/navigation";
import { notoSansKr } from "./font";
import BackToTopButton from "@/components/backToTopBtn";
import dynamic from "next/dynamic";

const CustomCursor = dynamic(() => import("@/components/AnimatedCursor"), {
  ssr: false,
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  return (
    <html lang="ko">
      <body className={notoSansKr.className}>
        {isClient && <CustomCursor />}
        <ConfigProvider>
          {children}
          <BackToTopButton />
        </ConfigProvider>
      </body>
    </html>
  );
}
