import ConfigProvider from "./config-provider";
import "./globals.css";
import Navigation from "@/components/navigation";
import { notoSansKr } from "./font";
// import Link from "next/link";
import BackToTopButton from "@/components/backToTopBtn";
// import ScrollContainer from "@/components/ SmoothContainer.component";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={notoSansKr.className}>
        <ConfigProvider>
          {/* <ScrollContainer> */}
          <Navigation />
          <div className="w-[1280px] mx-auto">{children}</div>
          <BackToTopButton />
          {/* </ScrollContainer> */}
        </ConfigProvider>
      </body>
    </html>
  );
}
