import ConfigProvider from "./config-provider";
import "./globals.css";
import Navigation from "@/components/navigation";
import { notoSansKr } from "./font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={notoSansKr.className}>
        <ConfigProvider>
          <Navigation />

          <div className="w-[1280px] mx-auto">{children}</div>
        </ConfigProvider>
      </body>
    </html>
  );
}
